name = "anime-video-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Production environment
[env.production]
name = "anime-video-proxy"
workers_dev = false

# Development environment
[env.development]
name = "anime-video-proxy-dev"
workers_dev = true
